import { imageMeta } from '../lib/images';

/**
 * <picture> with the AVIF/WebP srcsets and intrinsic size generated by
 * scripts/optimize-images.mjs. `src` is the public path used in content.js.
 */
export default function ResponsiveImage({
  src,
  alt,
  sizes,
  className,
  pictureClassName,
  loading = 'lazy',
  fetchPriority,
  style,
}) {
  const meta = imageMeta(src);
  return (
    <picture className={pictureClassName}>
      {meta?.sources.map((source) => (
        <source key={source.type} type={source.type} srcSet={source.srcset} sizes={sizes} />
      ))}
      <img
        src={src}
        alt={alt}
        width={meta?.width}
        height={meta?.height}
        className={className}
        style={style}
        loading={loading}
        decoding="async"
        fetchPriority={fetchPriority}
      />
    </picture>
  );
}
